#ifndef _KAKUSHI_ACTIVITY_H
#define _KAKUSHI_ACTIVITY_H

#define      /* ！ */    M_BI       33           
#define      /* ゛ */    M_AP       34           
#define      /* ↓ */     XX1        35            
#define      /* → */     M_SR       36           
#define      /* ■ */     XX2        37            
#define      /* ＠ */    X21        38           
#define      /* ？ */    M_QE       39           
#define      /* （ */    M_K1       40           
#define      /* ） */    M_K2       41           
#define      /* ＊ */    M_AT       42           
#define      /* ＋ */    M_PL       43           
#define      /* ， */    M_CN       44           
#define      /* － */    M_MI       45           
#define      /* ． */    M_PI       46           
#define      /* ／ */    M_SU       47           
#define      /* 0 */     M_00       48           
#define      /* 1 */     M_01       49           
#define      /* 2 */     M_02       50           
#define      /* 3 */     M_03       51           
#define      /* 4 */     M_04       52           
#define      /* 5 */     M_05       53           
#define      /* 6 */     M_06       54           
#define      /* 7 */     M_07       55           
#define      /* 8 */     M_08       56           
#define      /* 9 */     M_09       57           
#define      /* Ａ */    M_0A       58           
#define      /* Ｂ */    M_0B       59           
#define      /* Ｃ */    M_0C       60           
#define      /* Ｄ */    M_0D       61           
#define      /* Ｅ */    M_0E       62           
#define      /* Ｆ */    M_0F       63           
#define      /* ＠ */    XX3        64            
#define      /* ＠ */    XX4        65            
#define      /* ＠ */    XX5        66            
#define      /* ＠ */    XX6        67            
#define      /* ＠ */    XX7        68            
#define      /* ＠ */    XX8        69            
#define      /* ＠ */    XX9        70            
#define      /* Ｇ */    M_0G       71           
#define      /* Ｈ */    M_0H       72           
#define      /* Ｉ */    M_0I       73           
#define      /* Ｊ */    M_0J       74           
#define      /* Ｋ */    M_0K       75           
#define      /* Ｌ */    M_0L       76           
#define      /* Ｍ */    M_0M       77           
#define      /* Ｎ */    M_0N       78           
#define      /* Ｏ */    M_0O       79           
#define      /* Ｐ */    M_0P       80           
#define      /* Ｑ */    M_0Q       81           
#define      /* Ｒ */    M_0R       82           
#define      /* Ｓ */    M_0S       83           
#define      /* Ｔ */    M_0T       84           
#define      /* Ｕ */    M_0U       85           
#define      /* Ｖ */    M_0V       86           
#define      /* Ｗ */    M_0W       87           
#define      /* Ｘ */    M_0X       88           
#define      /* Ｙ */    M_0Y       89           
#define      /* Ｚ */    M_0Z       90           
#define      /* ＠ */    X10        91            
#define      /* ＠ */    X11        92            
#define      /* ＠ */    X12        93            
#define      /* ＠ */    X13        94            
#define      /* ＠ */    X14        95            
#define      /* ＠ */    X15        96            
#define      /* ＠ */    X16        97            
#define      /* ＠ */    X17        98            
#define      /* ＠ */    X18        99            
#define      /* ＠ */    X19        100           
#define      /* ＠ */    X20        101           
#define      /* を */    H_WO       102          
#define      /* ぁ */    X28        103           
#define      /* ぃ */    X29        104           
#define      /* ぅ */    X30        105           
#define      /* ぇ */    X31        106           
#define      /* ぉ */    X32        107           
#define      /* ゃ */    H_XA       108          
#define      /* ゅ */    H_XU       109          
#define      /* ょ */    H_XO       110          
#define      /* っ */    H_XT       111          
#define      /* 　 */    M_SP       112           
#define      /* あ */    H_AA       113          
#define      /* い */    H_II       114          
#define      /* う */    H_UU       115          
#define      /* え */    H_EE       116          
#define      /* お */    H_OO       117          
#define      /* か */    H_KA       118          
#define      /* き */    H_KI       119          
#define      /* く */    H_KU       120          
#define      /* け */    H_KE       121          
#define      /* こ */    H_KO       122          
#define      /* さ */    H_SA       123          
#define      /* し */    H_SI       124          
#define      /* す */    H_SU       125          
#define      /* せ */    H_SE       126          
#define      /* そ */    H_SO       127          
#define      /* た */    H_TA       128          
#define      /* ち */    H_TI       129          
#define      /* つ */    H_TU       130          
#define      /* て */    H_TE       131          
#define      /* と */    H_TO       132          
#define      /* な */    H_NA       133          
#define      /* に */    H_NI       134          
#define      /* ぬ */    H_NU       135          
#define      /* ね */    H_NE       136          
#define      /* の */    H_NO       137          
#define      /* は */    H_HA       138          
#define      /* ひ */    H_HI       139          
#define      /* ふ */    H_HU       140          
#define      /* へ */    H_HE       141          
#define      /* ほ */    H_HO       142          
#define      /* ま */    H_MA       143          
#define      /* み */    H_MI       144          
#define      /* む */    H_MU       145          
#define      /* め */    H_ME       146          
#define      /* も */    H_MO       147          
#define      /* や */    H_YA       148          
#define      /* ゆ */    H_YU       149          
#define      /* よ */    H_YO       150          
#define      /* ら */    H_RA       151          
#define      /* り */    H_RI       152          
#define      /* る */    H_RU       153          
#define      /* れ */    H_RE       154          
#define      /* ろ */    H_RO       155          
#define      /* わ */    H_WA       156          
#define      /* ん */    H_NN       157          
#define      /* ＠ */    X22        158           
#define      /* ＠ */    X23        159           
#define      /* ＠ */    X24        160           
#define      /* 。 */    H_MR       161          
#define      /* ＠ */    X25        162           
#define      /* ＠ */    X26        163           
#define      /* 、 */    H_TN       164          
#define      /* ＠ */    X27        165           
#define      /* ヲ */    K_WO       166          
#define      /* ァ */    K_X1        167           
#define      /* ィ */    X34        168           
#define      /* ゥ */    X35        169           
#define      /* ェ */    X36        170           
#define      /* ォ */    X37        171           
#define      /* ャ */    K_XA       172          
#define      /* ュ */    K_XU       173          
#define      /* ョ */    K_XO       174          
#define      /* ッ */    K_XT       175          
#define      /* ー */    K_BO       176          
#define      /* ア */    K_AA       177          
#define      /* イ */    K_II       178          
#define      /* ウ */    K_UU       179          
#define      /* エ */    K_EE       180          
#define      /* オ */    K_OO       181          
#define      /* カ */    K_KA       182          
#define      /* キ */    K_KI       183          
#define      /* ク */    K_KU       184          
#define      /* ケ */    K_KE       185          
#define      /* コ */    K_KO       186          
#define      /* サ */    K_SA       187          
#define      /* シ */    K_SI       188          
#define      /* ス */    K_SU       189          
#define      /* セ */    K_SE       190          
#define      /* ソ */    K_SO       191          
#define      /* タ */    K_TA       192          
#define      /* チ */    K_TI       193          
#define      /* ツ */    K_TU       194          
#define      /* テ */    K_TE       195          
#define      /* ト */    K_TO       196          
#define      /* ナ */    K_NA       197          
#define      /* ニ */    K_NI       198          
#define      /* ヌ */    K_NU       199          
#define      /* ネ */    K_NE       200          
#define      /* ノ */    K_NO       201          
#define      /* ハ */    K_HA       202          
#define      /* ヒ */    K_HI       203          
#define      /* フ */    K_HU       204          
#define      /* ヘ */    K_HE       205          
#define      /* ホ */    K_HO       206          
#define      /* マ */    K_MA       207          
#define      /* ミ */    K_MI       208          
#define      /* ム */    K_MU       209          
#define      /* メ */    K_ME       210          
#define      /* モ */    K_MO       211          
#define      /* ヤ */    K_YA       212          
#define      /* ユ */    K_YU       213          
#define      /* ヨ */    K_YO       214          
#define      /* ラ */    K_RA       215          
#define      /* リ */    K_RI       216          
#define      /* ル */    K_RU       217          
#define      /* レ */    K_RE       218          
#define      /* ロ */    K_RO       219          
#define      /* ワ */    K_WA       220          
#define      /* ン */    K_NN       221          
#define      /* ゛ */    K_DT       222          
#define      /* ゜ */    K_DM       223          
#define      /* ゛ */    H_DT       222          
#define      /* ゜ */    H_DM       223          
#define      /* 。 */    K_MR       161          
#define      /* 、 */    K_TN       164          

typedef struct {
	short Sx;
} KakushiActivityWork;

short KakushiInit(KakushiActivityWork *aw);
short KakushiUpdate(KakushiActivityWork *aw);

#endif